

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3307:3306"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/codingtutorial
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: vgola261@gmail.com
    depends_on:
      - db
    networks:
      - ems-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vgola261@gmail.com
      MYSQL_DATABASE: codingtutorial
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ems-network

volumes:
  db_data:

networks:
  ems-network:
    driver: bridge
