version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3030:3030"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql201.epizy.com:3306/if0_39124396_codingtutorial
      SPRING_DATASOURCE_USERNAME: if0_39124396
      SPRING_DATASOURCE_PASSWORD: vikasgola@07
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
