version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/codingtutorial
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: vgola261@gmail.com

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: employees_db
      MYSQL_USER: root
      MYSQL_PASSWORD: vgola261@gmail.com
      MYSQL_ROOT_PASSWORD: vgola261@gmail.com
    ports:
      - "3306:3306"
