version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ems-mysql
    environment:
      MYSQL_DATABASE: codingtutorial
      MYSQL_ROOT_PASSWORD: vgola261@gmail.com
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: ems-app
    ports:
      - "3030:3030"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/codingtutorial
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: vgola261@gmail.com
    networks:
      - ems-network

volumes:
  db_data:

networks:
  ems-network:
    driver: bridge
